INSERT INTO public.society (id, name, description, about, logo, cover) VALUES ('e90c3b36-c41e-43d1-a806-69cae4075e48', 'Character Building Society', 'Character Building Society (CBS) is the community of students focused on character development and fostering and culture of high moral standards.', 'about', 'https://cdn.statically.io/gh/bilalsohailmirza/participant-portal-frontend/bilal/assets/images/logos/cbs.jpg', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.society (id, name, description, about, logo, cover) VALUES ('7ce4fee9-439f-4d1d-9612-82dffe33987d', 'PROCOM', 'Procom is the biggest community of student that come together every year to host PROCOM, the flasghisp event of FAST - NUCES Kacrachi', 'Procom is a flagship event of FAST Karachi Campus that’s maintained its tradition from the past 25 years. The event is a means to promote a culture of community building,  engagement and to enclose the gap between the academia and the industry.
Multiple categories of competitions are held  where students from FAST and other institutes get to showcase their skills in a healthy competitive environment.

Another highlight of the event is the job fair where companies from across Pakistan show up for recruitment and engagement with the students.  There are discussion panels consisting of seasoned professionals where students can engage with them get insights into the industry.', 'https://cdn.statically.io/gh/bilalsohailmirza/participant-portal-frontend/bilal/assets/images/logos/procom.jpg', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.society (id, name, description, about, logo, cover) VALUES ('03bbd2a1-2914-4f07-ba49-3039aa57f40b', 'Dramatics & Extra Curricular Society', 'Dramatics & Extra Curricular Society (DECS) is the center of all the fun and extracurriculars in the campus. Whether it be dramatics, singing, travelling trips, all the fun is organized by DECS.', 'about', 'https://cdn.statically.io/gh/bilalsohailmirza/participant-portal-frontend/bilal/assets/images/logos/decs.jpg', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.society (id, name, description, about, logo, cover) VALUES ('af206207-3dba-4ddf-9e8d-8c234c393880', 'The Literary Club', 'The Literary Club (TLC) is a community consisting students that are passionate about art and literature. It is a community to explore your artistic passions and aspirations.', 'about', 'https://cdn.statically.io/gh/bilalsohailmirza/participant-portal-frontend/bilal/assets/images/logos/tlc.jpg', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.society (id, name, description, about, logo, cover) VALUES ('20156ae8-4724-49a7-a512-2ddd6edd1533', 'Association for Computing Machinery', 'ACM is the official student chapter of Association for Computing Machinery at FAST-NUCES Karachi. The biggest community of tech enthusiasts at NUCES Karachi.', 'about', 'https://cdn.statically.io/gh/bilalsohailmirza/participant-portal-frontend/bilal/assets/images/logos/acm.jpg', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.society (id, name, description, about, logo, cover) VALUES ('89d5be77-31ac-4d8e-9f8a-39ceb3d068eb', 'Think ‘n Create', 'Think ‘n Create is the community of creatives and individuals who dare to imagine beyond the the norms. ', 'about', 'https://cdn.statically.io/gh/bilalsohailmirza/participant-portal-frontend/bilal/assets/images/logos/tnc.jpg', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.society (id, name, description, about, logo, cover) VALUES ('5d70010f-b559-436a-a7ef-750b267b0ef2', 'Microsoft Learn Student Ambassadors', 'MLSA is the official student chapter of Microsoft Learn Student Ambassadors at NUCES Karachi.', 'about', 'https://cdn.statically.io/gh/bilalsohailmirza/participant-portal-frontend/bilal/assets/images/logos/mlsa.jpg', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.society (id, name, description, about, logo, cover) VALUES ('dd2d7e2f-9ea7-4d10-9e72-c66a6811b6e0', 'Google Developers Student Club', 'GDSC is the official student chapter of Google Deleopers Club at NUCES Karachi. It fosters the culture of technology and innovation at the campus.', 'about', 'https://cdn.statically.io/gh/bilalsohailmirza/participant-portal-frontend/bilal/assets/images/logos/gdsc.jpg', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.society (id, name, description, about, logo, cover) VALUES ('adc1e5f0-8c4e-4bad-a678-f7a12b13c07e', 'Fast Creators Crew', 'Fast Creators Crew (FCC) is the student community consisting of inviduals passionate about media creation and production. They are media ambassadors of the Campus.', 'about', 'https://cdn.statically.io/gh/bilalsohailmirza/participant-portal-frontend/bilal/assets/images/logos/fcc.jpg', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.society (id, name, description, about, logo, cover) VALUES ('6c4e50c7-b35d-4921-8db3-c704e15bb9b7', 'Fast Data Science Society', 'FDSS is the the community centered towards Data Science and Artificial Intelligence.', 'about', 'https://cdn.statically.io/gh/bilalsohailmirza/participant-portal-frontend/bilal/assets/images/logos/fdss.jpg', NULL) ON CONFLICT DO NOTHING;